version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
    build_and_test:
        docker:
            - image: circleci/node:14
        working_directory: ~/app
        steps:
            - checkout
            - run:
                  name: Install Frontend Dependencies
                  command: |
                      npm install
            - run:
                  name: Install Backend Dependencies
                  command: |
                      cd backend
                      npm install
            - run:
                  name: Build Frontend
                  command: |
                      npm run build
            - run:
                  name: Test Frontend
                  command: |
                      npm test


workflows:
  test: 
    jobs:
      - build_and_test
  build_and_deploy:
    jobs:
      - aws-ecr/build_and_push_image:
            auth:
                - aws-cli/setup:
                    role_arn: arn:aws:iam::797929460436:role/openid
                    role_session_name: example-session
            repo: mern-ludo
            public_registry: true
            tag: latest
            filters:
                branches:
                    only:
                        - main